$:
  push:
    - runner:
        cpus: 1
      imports: https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/github.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/huohuocn/good-zzz.git
            auth_type: https
            username: ${GIT_HUOUSERNAME}
            password: ${GIT_HUOACCESS_TOKEN}
            git_user: ${GIT_HUOUSERNAME}
            git_email: sdcom@sdcom.asia
            force: true
            branch: main