name: Build Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.windows.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --name="HDD-System" --windowed --icon=Icon.ico --add-data="*.png;." --add-data="*.mp3;." --add-data="*.wav;." --add-data="*.ttf;." --add-data="Icon.ico;." Main.PY

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: HDD-System-Windows
          path: dist/HDD-System/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.macos.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --name="HDD-System" --windowed --icon=Icon.ico --add-data="*.png:." --add-data="*.mp3:." --add-data="*.wav:." --add-data="*.ttf:." --add-data="Icon.ico:." Main.PY

      - name: Create DMG (macOS disk image)
        run: |
          # 安装create-dmg工具
          brew install create-dmg
          
          # 创建临时目录
          mkdir -p dmg_contents
          
          # 复制.app到临时目录
          cp -r dist/HDD-System.app dmg_contents/
          
          # 创建DMG文件
          create-dmg \
            --volname "HDD-System" \
            --volicon "Icon.ico" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon "HDD-System.app" 150 190 \
            --app-drop-link 450 190 \
            "HDD-System.dmg" \
            "dmg_contents/"

      - name: Upload macOS artifact (.app)
        uses: actions/upload-artifact@v3
        with:
          name: HDD-System-macOS-app
          path: dist/HDD-System.app/

      - name: Upload macOS artifact (.dmg)
        uses: actions/upload-artifact@v3
        with:
          name: HDD-System-macOS-dmg
          path: HDD-System.dmg